# Generated by Django 3.0.2 on 2020-05-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_glossario_defin'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossario',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
