# Generated by Django 3.0.2 on 2020-05-26 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_glossario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossario',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossario',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
