# Generated by Django 3.0.2 on 2020-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200525_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
