# Generated by Django 3.0.2 on 2020-06-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200527_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagem'),
        ),
    ]
