# Generated by Django 3.0.2 on 2020-06-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200605_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='definition',
            field=models.TextField(max_length=500, verbose_name='Definição'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='expression',
            field=models.CharField(max_length=100, verbose_name='Expressão'),
        ),
    ]
