# Generated by Django 3.0.2 on 2020-06-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200620_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glossario',
            new_name='Terminology',
        ),
    ]
