# Generated by Django 3.0.2 on 2020-07-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200630_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagem'),
        ),
    ]
