# Generated by Django 3.0.2 on 2020-07-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200630_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='image',
            field=models.ImageField(height_field=640, upload_to='media/', verbose_name='Imagem', width_field=620),
        ),
        migrations.AlterField(
            model_name='terminology',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
