# Generated by Django 3.0.2 on 2020-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200716_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
