# Generated by Django 3.0.2 on 2020-07-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200716_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='area',
            field=models.CharField(choices=[('CET', 'Ciências exatas e da terra'), ('CB', 'Ciências biológicas'), ('EG', 'Engenharias'), ('CS', 'Ciências da saúde'), ('CA', 'Ciências agrárias'), ('CSA', 'Ciências sociais e aplicadas'), ('CH', 'Ciências humanas'), ('LLA', 'Linguística, letras e artes'), ('OT', 'Outros')], max_length=30, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='terminology',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
