# Generated by Django 3.0.2 on 2020-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200719_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='area',
            field=models.CharField(choices=[('CE', 'Ciências exatas e da terra'), ('CB', 'Ciências biológicas'), ('EG', 'Engenharias'), ('CS', 'Ciências da saúde'), ('CA', 'Ciências agrárias'), ('SA', 'Ciências sociais e aplicadas'), ('CH', 'Ciências humanas'), ('LL', 'Linguística, letras e artes'), ('OT', 'Outros')], max_length=30, verbose_name='Área'),
        ),
    ]
