# Generated by Django 3.0.2 on 2020-07-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200721_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='area',
            field=models.CharField(choices=[('Ciências exatas e da terra', 'Ciências exatas e da terra'), ('Ciências biológicas', 'Ciências biológicas'), ('Engenharias', 'Engenharias'), ('Ciências da saúde', 'Ciências da saúde'), ('Ciências agrárias', 'Ciências agrárias'), ('Ciências sociais e aplicadas', 'Ciências sociais e aplicadas'), ('Ciências humanas', 'Ciências humanas'), ('Linguística, letras e artes', 'Linguística, letras e artes'), ('Outros', 'Outros')], max_length=30, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='terminology',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug (adicionado automaticamente)'),
        ),
    ]
