# Generated by Django 3.0.2 on 2020-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200527_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='assunto',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='---', max_length=50, verbose_name='Assunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
